### PR TITLE
Enable contributor mode

### PR DESCRIPTION
**Pull request by rvillablanca**
#### Summary

Currently there is a campaign to migrate all `*model.AppError` errors returned in the store layer to be plain errors. This implies we have to rename some message keys from `"store.sql_channel..."` to `"app.channel..."` and then sort all this message keys in `en.json` translation file. 

When you need to migrate several methods from a store type in one shot you have to rename and then sort all message keys manually, this is because running the command `make extract` will remove all enterprise message keys since a contributor doesn't have access to enterprise repository.

This PR add a new flag to `extract` command named `--contributor` which allows to contributors to run the command without removing all enterprise keys.

I decided to not modify the current so it will continue working as expected, then you could add some task in the makefile using the flag `--contributor` allowing contributors to reorganize the translation file `en.json`.

### CODE REVIEW

**Review by hanzei — APPROVED** [review]
Awesome, thanks for stepping up and helping the community! It how this has been a PITA for community members.

**Comment by jespino** [comment]
This is great, but first we need to review all the enterprise code to be sure there are not translation strings without ent prefix. I'll check it and come back to this.

**Review by jespino — APPROVED** [review]
Great work @rvillablanca! looks good to me, but have to wait until a couple of PR related to this are merged in master.

**Comment by agnivade** [comment]
@jespino - The EE repo is fixed now right? Is there anything else blocking this?

**Comment by jasonblais** [comment]
cc @jespino as a reminder for above note when you come back from PTO next week

**Comment by rvillablanca** [comment]
Conflicts resolved

**Comment by jespino** [comment]
@rvillablanca Thanks! now is merged, sorry the delay, I think this is going to help you and other contributors :tada:

**Pull request merged**
