### PR TITLE
Remove 'hacktoberfest' label from new help wanted issues

### PR DESCRIPTION
**Pull request by jasonblais**
@metanerd ready for your review

### CODE REVIEW

**Review by metanerd — APPROVED** [review]

**Comment by metanerd** [comment]
Since we now use terraform for github management, I am not sure this is the right place to modify this label. But I know there still was a service running in the k8s cluster of cloud with this code.

**Review by jaydeland — APPROVED** [review]

**Comment by jasonblais** [comment]
> Since we now use terraform for github management, I am not sure this is the right place to modify this label. But I know there still was a service running in the k8s cluster of cloud with this code.

@metanerd let me know if there's an action for me to take to have this change applied?

**Comment by jasonblais** [comment]
@metanerd I currently see the `Hacktoberfest` label added for new Help Wanted issues, e.g. https://github.com/mattermost/mattermost-server/issues/16750

Not sure if we need to deploy the script somewhere to take effect?

**Comment by cpanato** [comment]
on it

**Pull request merged**
