### PR TITLE
Added support for customer-web-portal to mmgotool

### PR DESCRIPTION
**Pull request by reflog**
#### Summary
added option for translation pattern used in customer-web-portal
added option to skip dynamically translated strings (only useful in webapp/server)
moved to go modules

### CODE REVIEW

**Comment by reflog** [comment]
@jespino - maybe move this code to v2 subfolder or something to avoid build issues in projects using mmgotool?

**Comment by jespino** [comment]
Shouldn't it be backward compatible? I don't see any breaking changes.

Other thing, how I express that I want to extract from web-portal? (like --enterprise-dir option).

**Comment by reflog** [comment]
@jespino - i'm not sure honestly. right now we install it with GO111MODULES=off ...
Regarding the other options - there's no need in them, using `mattermost-dir` works fine for the portal (similar structure, etc).
If you feel like it needs to be separated - I can do that

**Comment by jespino** [comment]
@reflog the point for me is, we are mixing things there it is not a "mattermost-dir" it is a "portal-dir" and you can detect things like, if you are passing portal-dir I don't allow you to pass `mattermost-dir` or `enterprise-dir` for example. If you don't pass anything, it should detect that you are using the portal, and do not allow to extract things from the enterprise dir, even if there is an `enterprise` folder in the `../` path. My concern is about making things unclear and error prone. We can discuss this in Jitsi tomorrow if you want.

About the version, if it works without changing the version, I would keep that without changing the version, because the changes looks backward compatible,  and is an internal tool. If it doesn't work, we can decide to go for the v2.

**Comment by reflog** [comment]
@jespino - backwards compatibility seems to be ok.
I've added separate argument per your suggestion

**Review by jespino — APPROVED** [review]

**Pull request merged**
